various bugfix commits:
- subscription tenant display error (the same as hotfix commit, see pull request 320)
- for ERMS-1093: KBart column headers are now matched case-insensitive; try-catch-block introduced to catch NoClassDefFoundError